HomeMedicalKit/urls.py
from django.contrib import admin
from django.urls import path, include
from MedicinesAppHandler import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('MedicinesAppHandler/', include('MedicinesAppHandler.urls')),
    path('', views.start_view, name='start'),
]

MedicinesAppHandler/urls.py
from django.urls import path
from . import views

# URLConf
urlpatterns = [
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/signup/', views.signup_view, name='signup'),
    path('medicines/', views.medicine_list, name='medicine_list'),
    path('medicines/add/', views.medicine_add, name='medicine_add'),
    path('medicines/<int:pk>/edit/', views.medicine_edit, name='medicine_edit'),
    path('medicines/<int:pk>/delete/', views.medicine_delete, name='medicine_delete'),
    path('medicines/import', views.import_medicines_from_csv, name='import_medicines_from_csv'),
    path('medicines/export/', views.export_medicines_csv, name='export_medicines_csv'),
    path('medicines/side_effects_list/', views.side_effects_list, name='side_effects_list'),
    path('medicines/side_effects_chart/', views.side_effects_chart, name='side_effects_chart'),
    path('start/', views.start_view, name='start'),
    path('home/', views.home_view, name='home'),
]

MedicinesAppHandler/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models


class User(AbstractUser):
    firstname = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)

    def __str__(self):
        return self.username


class MedicineName(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Medicine(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)  # Example default value, adjust as needed
    name = models.ForeignKey(MedicineName, on_delete=models.CASCADE)
    purpose = models.CharField(max_length=255)
    quantity = models.IntegerField()
    expiration_date = models.DateField()

    def __str__(self):
        return f'{self.name} ({self.quantity}) - Expires on {self.expiration_date}'


class SideEffect(models.Model):
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    description = models.TextField()

    def __str__(self):
        return self.description


class Substance(models.Model):
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

MedicinesAppHandler/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User, Medicine, SideEffect, Substance
from django.forms.widgets import PasswordInput, TextInput


class SignUpForm(UserCreationForm):
    firstname = forms.CharField(max_length=100, required=False, help_text='Optional.')
    lastname = forms.CharField(max_length=100, required=False, help_text='Optional.')

    class Meta:
        model = User
        fields = ['username', 'password1']


class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())


class MedicineForm(forms.ModelForm):
    class Meta:
        model = Medicine
        fields = ['name', 'purpose', 'quantity', 'expiration_date']


class SideEffectForm(forms.ModelForm):
    class Meta:
        model = SideEffect
        fields = ['description']


class SubstanceForm(forms.ModelForm):
    class Meta:
        model = Substance
        fields = ['name']

MedicinesAppHandler/views.py
from django.http import HttpResponse, FileResponse
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import auth
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import User, Medicine, SideEffect
from .forms import SignUpForm, LoginForm, MedicineForm, SideEffectForm
from .utils import import_medicine_names_from_csv
import matplotlib.pyplot as plt
import csv
import io


def start_view(request):
    return render(request, 'start.html')


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            messages.success(request, 'Konto zostało utworzone pomyślnie!')
            return redirect('home')  # Przekierowanie na stronę po zalogowaniu
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')  # Przekierowanie na stronę po zalogowaniu
            else:
                messages.error(request, 'Nieprawidłowy email lub hasło.')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('login')  # Przekierowanie na stronę logowania po wylogowaniu


@login_required
def home_view(request):
    return render(request, 'home.html')


@login_required
def import_medicines_from_csv(request):
    if request.method == 'POST' and request.FILES.get('csv_file'):
        csv_file = request.FILES['csv_file']
        try:
            import_medicine_names_from_csv(csv_file)
            messages.success(request, 'Rekordy zostały pomyślnie zaimportowane do bazy danych.')
        except Exception as e:
            messages.error(request, f'Wystąpił błąd podczas importowania rekordów: {str(e)}')
    return render(request, 'import_medicines.html')


@login_required
def medicine_list(request):
    medicines = Medicine.objects.filter(user=request.user)

    # Pobierz liczbę wyników na stronie z parametru GET (jeśli dostępny)
    results_per_page = request.GET.get('results_per_page', 10)  # domyślnie 10 wyników na stronie
    paginator = Paginator(medicines, results_per_page)

    page = request.GET.get('page')
    try:
        medicines = paginator.page(page)
    except PageNotAnInteger:
        medicines = paginator.page(1)
    except EmptyPage:
        medicines = paginator.page(paginator.num_pages)

    return render(request, 'medicines_list.html', {'medicines': medicines, 'results_per_page': results_per_page})


@login_required
def medicine_add(request):
    if request.method == 'POST':
        form = MedicineForm(request.POST)
        if form.is_valid():
            medicine = form.save(commit=False)
            medicine.user = request.user
            medicine.save()
            return redirect('medicine_list')
    else:
        form = MedicineForm()
    return render(request, 'medicines_form.html', {'form': form})


@login_required
def medicine_edit(request, pk):
    medicine = get_object_or_404(Medicine, pk=pk, user=request.user)
    if request.method == 'POST':
        form = MedicineForm(request.POST, instance=medicine)
        if form.is_valid():
            form.save()
            return redirect('medicine_list')
    else:
        form = MedicineForm(instance=medicine)
    return render(request, 'medicines_form.html', {'form': form})


@login_required
def medicine_delete(request, pk):
    medicine = get_object_or_404(Medicine, pk=pk, user=request.user)
    if request.method == 'POST':
        medicine.delete()
        return redirect('medicine_list')
    return render(request, 'medicines_confirm_delete.html', {'medicine': medicine})


@login_required
def export_medicines_csv(request):
    medicines = Medicine.objects.filter(user=request.user)
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="medicines.csv"'
    writer = csv.writer(response)
    writer.writerow(['Name', 'Purpose', 'Quantity', 'Expiration Date'])
    for medicine in medicines:
        writer.writerow([medicine.name, medicine.purpose, medicine.quantity, medicine.expiration_date])
    return response


@login_required
def side_effects_list(request):
    side_effects = SideEffect.objects.filter(medicine__user=request.user)

    # Pobierz liczbę wyników na stronie z parametru GET (jeśli dostępny)
    results_per_page = request.GET.get('results_per_page', 10)  # domyślnie 10 wyników na stronie
    paginator = Paginator(side_effects, results_per_page)

    page = request.GET.get('page')
    try:
        side_effects = paginator.page(page)
    except PageNotAnInteger:
        side_effects = paginator.page(1)
    except EmptyPage:
        side_effects = paginator.page(paginator.num_pages)

    return render(request, 'side_effects_list.html',{'side_effects': side_effects, 'results_per_page': results_per_page})


@login_required
def side_effects_chart(request):
    medicines = Medicine.objects.filter(user=request.user)
    side_effects_count = {medicine.name: medicine.sideeffect_set.count() for medicine in medicines}

    plt.bar(side_effects_count.keys(), side_effects_count.values())
    plt.xlabel('Medicines')
    plt.ylabel('Number of Side Effects')
    plt.title('Number of Side Effects for Each Medicine')

    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    buf.seek(0)
    return FileResponse(buf, as_attachment=True, filename='side_effects_chart.png')

MedicinesAppHandler/templates/add_side_effect.html
{% extends 'base.html' %}

{% block title %}
Add Side Effect
{% endblock %}

{% block header %}
Witaj, {{ user.username }}!
{% endblock %}

{% block content %}
  <h1 class="form-heading">Add Side Effect for {{ medicine.name }}</h1>
  <form method="post" class="form-style">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="submit-button">Save</button>
  </form>
{% endblock %}

MedicinesAppHandler/templates/add_substance.html
{% extends 'base.html' %}

{% block title %}
Add Substance
{% endblock %}

{% block header %}
Witaj, {{ user.username }}!
{% endblock %}

{% block content %}
    <h1 class="form-heading">Add Substance for {{ medicine.name }}</h1>
    <form method="post" class="form-style">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit" class="submit-button">Save</button>
    </form>
{% endblock %}

MedicinesAppHandler/templates/home.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block header %}
Witaj, {{ user.username }}!
{% endblock %}

{% block content %}
    <h3 class="main-home-heading">Witaj na stronie głównej aplikacji. Jesteś zalogowany jako {{ user.username }}.</h3>
{% endblock %}

MedicinesAppHandler/templates/import_medicines.html
{% extends "base.html" %}

{% block title %}
Import Leków
{% endblock %}

{% block header %}
Witaj, {{ user.username }}!
{% endblock %}

{% block content %}
    <h2 class="form-heading">Importuj Leki z pliku CSV</h2>

    <form method="post" enctype="multipart/form-data" class="form-style">
        {% csrf_token %}
        <div class="input-file-container">
            <label for="csv_file" class="custom-file-label">Wybierz plik</label>
            <input type="file" id="csv_file" name="csv_file" class="input-file">
        </div>
        <button type="submit" class="submit-button">Importuj</button>
    </form>
{% endblock %}

MedicinesAppHandler/templates/import_medicines_names_from_csv.html
{% extends "base.html" %}

{% block title %}
Import Leków
{% endblock %}

{% block header %}
Witaj, {{ user.username }}!
{% endblock %}

{{% block content %}
    <h1 class="form-heading">Importuj nazwy leków z bazy danych</h1>

    <form method="post" enctype="multipart/form-data" class="form-style">
        {% csrf_token %}
        <input type="file" name="csv_file" accept=".csv" required>
        <button type="submit" class="submit-button">Importuj</button>
    </form>

    <a href="{% url 'medicines_names_list' %}" class="link-button">Powrót</a>
{% endblock %}

MedicinesAppHandler/templates/login.html
{% extends "base.html" %}

{% block title %}
Logowanie
{% endblock %}

{% block content %}
    <h2 class="form-heading">Logowanie</h2>
    <form action="{% url 'login' %}" method="POST" class="form-style">
        {% csrf_token %}
        {% if messages %}
            {% for message in messages %}
                <div>{{message}}</div>
            {% endfor %}
        {% endif %}
        <br>
        <label for="username">Nazwa Użytkownika:</label>
        <input type="text" name="username" value="" id="username" required>
        <br><br>
        <label for="password">Hasło:</label>
        <input type="password" name="password" value="" id="password" required>
        <br><br>
        <input type="submit" class="submit-button" value="Zaloguj">
    </form>
{% endblock %}

MedicinesAppHandler/templates/medicine_detail.html
{% extends 'base.html' %}

{% block title %}
Details
{% endblock %}

{% block header %}
Witaj, {{ user.username }}!
{% endblock %}

{% block content %}
    <a href="{% url 'medicine_list' %}" class="link-button">Powrót</a>
    <h1 class="form-heading">{{ medicine.name }}</h1>
    <p>Purpose: {{ medicine.purpose }}</p>
    <p>Quantity: {{ medicine.quantity }}</p>
    <p>Expiration Date: {{ medicine.expiration_date }}</p>

    <h2 class="form-heading">Side Effects</h2>
    <ul>
      {% for side_effect in medicine.sideeffect_set.all %}
        <li>{{ side_effect.description }}
            <a href="{% url 'delete_side_effect' side_effect.id %}">Delete</a>
        </li>
      {% endfor %}
    </ul>
    <a href="{% url 'add_side_effect' medicine.id %}" class="link-button">Add Side Effect</a>

    <h2 class="form-heading">Substances</h2>
    <ul>
      {% for substance in medicine.substance_set.all %}
        <li>{{ substance.name }}
            <a href="{% url 'delete_substance' substance.id %}">Delete</a>
        </li>
      {% endfor %}
    </ul>
    <a href="{% url 'add_substance' medicine.id %}" class="link-button">Add Substance</a>
{% endblock %}

MedicinesAppHandler/templates/medicine_name_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Usuwanie nazwy leku</h1>
    <p>Czy na pewno chcesz usunąć nazwę leku "{{ medicine.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Potwierdź usunięcie</button>
        <a href="{% url 'medicines_names_list' %}" class="link-button">Anuluj</a>
    </form>
{% endblock %}

MedicinesAppHandler/templates/medicines_confirm_delete.html
{% extends "base.html" %}

{% block title %}
Usuń Lek
{% endblock %}

{% block content %}
    <h2>Jesteś pewien, że chcesz usunąć lek {{ medicine.name }}?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Usuń</button>
    </form>
    <a href="{% url 'medicine_list' %}">Anuluj</a>
{% endblock %}

MedicinesAppHandler/templates/medicines_form.html
{% extends "base.html" %}

{% block title %}
Dodaj/Edytuj Lek
{% endblock %}

{% block content %}
    <h2 class="form-heading">{% if form.instance.pk %}Edytuj{% else %}Dodaj{% endif %} Lek</h2>
    <form method="post" class="form-style">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit-button">Zapisz</button>
    </form>
{% endblock %}

MedicinesAppHandler/templates/medicines_list.html
{% extends "base.html" %}

{% block title %}
Leki
{% endblock %}

{% block header %}
Witaj, {{ user.username }}!
{% endblock %}

{% block content %}
    <h2 class="table-heading">Twoje Leki</h2>
    <form method="get" action="{% url 'medicine_list' %}" class="form-style">
        <label for="results_per_page">Liczba wyników na stronie:</label>
        <input type="number" id="results_per_page" name="results_per_page" min="1" value="{{ results_per_page }}">
        <button type="submit" class="submit-button">Zmień</button>
    </form>
    <a href="{% url 'import_medicines_from_csv' %}" class="link-button">Zczytaj leki z recepty</a>
    <a href="{% url 'medicine_add' %}" class="link-button">Dodaj Nowy Lek</a>
    <a href="{% url 'export_medicines_csv' %}" class="link-button">Eksportuj do CSV</a>
    <table class="table-style">
        <thead>
            <tr>
                <th>Nazwa</th>
                <th>Przeznaczenie</th>
                <th>Ilość</th>
                <th>Data ważności</th>
                <th>Akcje</th>
            </tr>
        </thead>
        <tbody>
            {% for medicine in medicines %}
                <tr>
                    <td>{{ medicine.user_id }}</td>
                    <td>{{ medicine.name }}</td>
                    <td>{{ medicine.purpose }}</td>
                    <td>{{ medicine.quantity }}</td>
                    <td>{{ medicine.expiration_date }}</td>
                    <td>
                        <a href="{% url 'medicine_edit' medicine.pk %}">Edytuj</a>
                        <a href="{% url 'medicine_delete' medicine.pk %}">Usuń</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

MedicinesAppHandler/templates/medicines_names_list.html
{% extends 'base.html' %}

{% block title %}
Medicines Names List
{% endblock %}

{% block header %}
Witaj, {{ user.username }}!
{% endblock %}

{% block content %}
    <h1 class="form-heading">Lista Nazw Leków</h1>

    <form method="get" class="form-style">
        {{ search_form.as_p }}
        <button type="submit" class="submit-button">Filtruj</button>
    </form>

    <br>

    <form method="get" class="form-style">
        {{ records_form.as_p }}
        <button type="submit" class="submit-button">Ustaw liczbę rekordów na stronie</button>
    </form>

    <a href="{% url 'import_medicines_names_from_csv' %}" class="link-button">Wczytaj leki z bazy danych</a>
    <a href="{% url 'medicine_list' %}" class="link-button">Powrót</a>

    <div class="table-container">
        <div class="table-style">
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nazwa Leku</th>
                        <th>Akcje</th>
                    </tr>
                </thead>
                <tbody>
                    {% for medicine in medicines %}
                        <tr>
                            <td>{{ medicine.id }}</td>
                            <td>{{ medicine.name }}</td>
                            <td>
                                <form method="post" action="{% url 'medicine_name_delete' medicine.id %}">
                                    {% csrf_token %}
                                    <button type="submit" onclick="return confirm('Czy na pewno chcesz usunąć tą nazwę leku?')">Usuń</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

MedicinesAppHandler/templates/side_effects_chart.html
{% extends 'base.html' %}

{% block header %}
Witaj, {{ user.username }}!
{% endblock %}

{% block content %}
    <h1 class="form-heading">Wykres działań niepożądanych dla wszystkich dodanych leków</h1>
    <img src="{{ image_url }}" alt="Side Effects Chart" class="center-image">
    <a href="{% url 'download_side_effects_pdf' %}" class="link-button">Pobierz dane z wykresu jako pdf</a>
    <a href="{% url 'medicine_list' %}" class="link-button">Powrót</a>
{% endblock %}

MedicinesAppHandler/templates/signup.html
{% extends "base.html" %}

{% block title %}
Rejestracja
{% endblock %}

{% block content %}
    <h2 class="form-heading">Rejestracja</h2>
    <form method="POST" class="form-style">
        {% csrf_token %}
        {% if messages %}
            {% for message in messages %}
                <div class="message">{{message}}</div>
            {% endfor %}
        {% endif %}
        {{ form.as_p }}
        <button type="submit" class="submit-button">Zarejestruj się</button>
    </form>
{% endblock %}